### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [jeffwalter/zsh-jwalter#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by itsjohannawren** [comment]
Added in https://github.com/jeffwalter/zsh-jwalter/pull/2

**Comment by unixorn** [comment]
Thanks!
